### ISSUE TITLE
Fetch member belongs to an organization

### ISSUE THREAD

**Issue by nguyendn** [OfficeDev/BotBuilder-MicrosoftTeams#114]
From what I know, if we want to send 1:1 message to all members of an organization, we need to do so:

1. Create a team which include all members
2. Add a bot to that team
3. The bot will fetch team rooster and start 1:1 dialog 

`connector.fetchMembers(serviceUrl, conversationId, function (err, result) {}`

Is that the only way? Can we just register a personal bot for all members by Team Admin?

**Comment by billbliss** [comment]
That is currently the only way, yes.

We have been looking at ways to make "proactive messaging" (that's what we call this) simpler but that's not available yet.

When we do, there will need to be controls over the scenario you describe - tenant administrators will want the ability to monitor and disable scenarios such as this because otherwise it's yet another vector for spam.

**Comment by nguyendn** [comment]
Thank you!
