### ISSUE TITLE
Support for List Card type.

### ISSUE THREAD

**Issue by Ky7m** [OfficeDev/BotBuilder-MicrosoftTeams#115]
There is a specific type of card type - [list card](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#list-card) that is supported only by Bots in Teams (no support in bot framework). Do you have plans to add support for this card type? 
Let me know if you accept PR :)

**Comment by billbliss** [comment]
This is actually a question for the main [BotBuilder SDK](https://github.com/Microsoft/BotBuilder).

But I can answer it here - the reason the List card was implemented is because we needed a richer UI for our Who bot, and we decided to open it up to developers too. I do not expect it to be implemented in any other bot platform.
