### ISSUE TITLE
User not able to see anything (Error), when Bot Service returns status code 403

### ISSUE THREAD

**Issue by imailer2015** [OfficeDev/BotBuilder-MicrosoftTeams#122]
## Bot Info
* SDK Platform: Bot REST Connector
* SDK Version: N.A.
* Active Channels: MS Teams
* Deployment Environment: Own deployment environment

## Issue Description
Hi Folks,

I was trying out authentication for Microsoft Bot messages and noticed that user doesn't receives any notification / message / error when the request is rejected with HTTP  403 (forbidden).

User should be able to see something / error for that.

This issue is particular to MS-Teams channel. Works fine on emulator and webchat (tried these 3 so far).

## Reproduction Steps
1. Create a bot with Microsoft and use the app id / password to configure you simple bot service.
2. User sends "Hi" message from the bot. Bot Connector makes a post request to the bot service endpoint.
3. Try explicitly sending HTTP 403 message as status for the request.
4. User doesn't see anything / Error on the chat UI.

## Expected Behavior
User should be able to see some error message indicating the message wasn't sent/delivered

## Actual Results
User is not able to see anything. It appears to user as if the message has been sent.

**Comment by billbliss** [comment]
This is a really good suggestion. The challenge is that the topology of message delivery is quite different across emulator, web chat, and Teams. When the user sends a message to the bot, our bot message service accepts it and responds with 200 OK. The message then fans out to the actual recipients later, so the 403 that you return is not fanned out to the recipients. We would have to change that logic to honor it, in effect generating a system-generated message in response to any bot message.

We've added a feature to the backlog to track this, but in all honesty you are the first to report this and until we hear about this from more developers, we likely won't get to this in a while. It requires a change on all our front end clients as well as the service side, because in effect this requires us to say "OK, user message received" but then change it later to "oops, this didn't go through, would you like to retry?" like web chat and the emulator do.
