### ISSUE TITLE
Not compatible with latest version of BotBuilder

### ISSUE THREAD

**Issue by ShakeySnake** [OfficeDev/BotBuilder-MicrosoftTeams#142]
I'm trying to implement our bot on a Service Fabric API, but there are conflicts with the JSON JWToken libraries, where the OpenID libraries that are part of Service Fabric require a later version. The teams version is constrained. Updating to a newer version of the BotBuilder package should solve this problem, but it seems some changes need to be made to some methods in this project.

**Comment by ShakeySnake** [comment]
Getting some details now.

**Comment by ShakeySnake** [comment]
The current version of Microsoft.Bot.Connector.Teams seems to have a hard dependency on Microsoft.Bot.Builder 3.5.9. When I try to upgrade to the later versions of Bot.Builder(currently 3.16.1.38846), I'm getting an error that Microsoft.BotConnector.Teams cannot find 3.5.9, even though the nuget says that it is compatible with Microsoft.Bot.Builder (>= 3.5.9 && < 4.0.0). 

The problem is that this older Bot.Builder version has a pretty stiff dependency on the older System.IdentityModel.Tokens.Jwt (>= 4.0.4.403061554 && < 5.0.0). The newer versions used by Active Directory libraries are 5.1.4 or greater.

Also, for experimentation sake, I cloned the Microsoft.Bot.Connector.Teams source and attempted to upgrade the packages. This cause several method signatures from Bot.Builder to change.  and one method, HandleErrorAsync seems to be removed from the modern version of Microsoft.Bot.Connector.

**Comment by billbliss** [comment]
This is super helpful, thanks!

**Comment by billbliss** [comment]
Our SDK developer found out what's going on. 

**Why this is happening**
Ideally when you add a nuget package, nuget package manager adds an AssemblyRedirect. This however tends to only happen for the main library in a package. Since the Microsoft.Bot.Builder old package had multiple dlls in the same package the assembly redirect is not getting generated at all. The weird part is it is not getting generated for Microsoft.Bot.Builder dll either. So the probe is looking for the version of dll which was used at compile time.
 
**Workaround**
Adding a assembly redirect manually will fix this. 

```xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Bot.Connector" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.16.1.38846" newVersion="3.16.1.38846" />
      </dependentAssembly>
```

At the moment we don't know a way to fix this without the manual workaround, but we'll keep looking. In the meantime this should unblock you.

**Comment by RamjotSingh** [comment]
Closing this issue. Please reopen if needed.

**Comment by tsahi** [comment]
FYI: The workaround can't be implemented in a Functions bot, where there is no binding redirect.

**Comment by ShakeySnake** [comment]
I had meant to re-open this., As the workaround didn't really work, and some methods are not compatible with versions of the bot framework beyond 3.5.9, even though the solution might compile.

For example: IConversations.UpdateActivityAsync will through a MissingMethodException at runtime pointing at an underlying constructor that no longer exists in new versions of the Bot Framework. In order to get this method to work, we had to down-rev back to 3.5.9.

This is with version v0.9.0.

**Comment by billbliss** [comment]
Our SDK does not currently support Bot Framework 4.x. We are working on it but don't have a date yet.
