### ISSUE TITLE
App studio is broken for messaging extensions 

### ISSUE THREAD

**Issue by rjgmail88** [OfficeDev/BotBuilder-MicrosoftTeams#152]
I am following a [document](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions) to create a messaging extension.

In App studio when I fill up all the details for manifest and, give extension name and click 'CREATE' button I see following error. 

![image](https://user-images.githubusercontent.com/32375467/46499413-a5543e80-c7e5-11e8-9a1d-37c6339255f6.png)

**Comment by goelashish7** [comment]
Are you able to repro it in Web client as well? Any errors in console ?

**Comment by jialic** [comment]
hey @rjgmail88 , can you verify if you can create an app on https://apps.dev.microsoft.com/

**Comment by rjgmail88** [comment]
Hey @jialic , In our organization only tenant admins have privilege to create an app and generate App ID / password on https://apps.dev.microsoft.com/ and this is using my AAD corp. account.
I use same account in Ms team client where I used App studio to do other stuff our Bot App. 

Hope this helps.

**Comment by jialic** [comment]
@rjgmail88, when you use App Studio to create a messaging extension or bot, we would create an AAD app for you under the hood (as the account you use to login to Teams). However, this respects the policies set up by your tenant admin. In this case, App Studio crashes because your account have insufficient privilege to create an AAD app.

We're planning a fix to show a better error message instead of crashing App Studio when this happens, but that wouldn't bypass the tenant policy.

In your case, you need to somehow get an AAD application created, then go to https://aka.ms/newteamsbot to create a new bot and add Microsoft Teams channel to the bot. Then, when you setup a bot/messaging extension in App Studio, choose the "Use Existing" flow and enter the AAD application ID you created.

**Comment by rjgmail88** [comment]
@jialic , thank you for the detailed flow and the explanation.
