### ISSUE TITLE
TypeError when using TeamsChatConnector.fetchMembers

### ISSUE THREAD

**Issue by ahleeny** [OfficeDev/BotBuilder-MicrosoftTeams#181]
Hi there,

After the update to v0.2.5 with botbuilder-teams, it seems like there is an issue with fetching members information:

TypeError: Class constructor ServiceClient cannot be invoked without 'new' 
at new RestClient
at TeamsChatConnector.fetchMembers 

Help would be much appreciated! Thank you.

**Comment by YKdvd** [comment]
I just started working with an example Teams bot (nodejs) tonight, and ran into this problem trying to retrieve the info for the message sender.  I reverted back to requiring botbuilder-teams 0.2.4, and things worked.  Just my luck I guess to start in on this a few days after a broken release got pushed.

It doesn't look like fetchMembers has a test?  My bot is running on Azure (I just created a free account for this test), and seems to have been provisioned with node 6.9.1/npm 3.10.8, FWIW.

**Comment by RamjotSingh** [comment]
@robin-liao Can you take a look?

**Comment by robin-liao** [comment]
Acknowledged. Will take a look.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andylwelch** [comment]
Hi guys,
I just ran into this same issue. I thought I would share my findings. I believe it was caused by the change of version of the ms-rest package from `v1.15.7` to `v2.3.8` in [this commit](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/commit/09d40957bb7360f3fa22aeaff2c0d31a5fc349a0).

[RestClient.js](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/Node/src/RemoteQuery/RestClient.js) is using ms-rest/ServiceClient.
ServiceClient was just exporting an extended function, now it exports a class on [line 134](http://azure.github.io/azure-sdk-for-node/ms-rest/latest/lib_serviceClient.js.html).

Seems like you guys may have been [here before](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/pull/86)?

I'll use 0.2.4 for now.
