### ISSUE TITLE
Dependency ms-rest-js renamed and causing errors

### ISSUE THREAD

**Issue by simonagren** [OfficeDev/BotBuilder-MicrosoftTeams#190]
Hi.
The ms-rest-js depency of the npm package botbuilder-teams has been renamed to @azure/ms-rest-js

So with version 4.0.0-beta1 I'm getting errors.
But changing to @azure/ms-rest-js in `node_modules\botbuilder-teams\lib\connector\teamsConnectorClientContext.js` and `node_modules\botbuilder-teams\lib\schema\operations\teams.js` made it work for me.

/Simon

**Comment by billbliss** [comment]
We think this has been fixed in a later version. See [here](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/issues/11) for more discussion on the details.

Try this and see if it fixes it:

1. Remove all the node_modules (e.g. `rm -rf node_modules` using bash)
2. Install a newer botbuilder SDK: `npm i botbuilder@4.3.0-beta1 --save-dev`
