### ISSUE TITLE
No event show up when user uninstall Bot

### ISSUE THREAD

**Issue by nguyendn** [OfficeDev/BotBuilder-MicrosoftTeams#228]
#### How to reproduce:

1. Install Bot in person context

<img width="284" alt="Screen Shot 2020-04-01 at 1 59 43 PM" src="https://user-images.githubusercontent.com/1620357/78186148-126b8300-7421-11ea-8a46-d7e839072c76.png">

2. There is an event like so

```
{ membersAdded: 
[ { id: '28:f56a1d76-2630-4200-bedc-fdff8a7672a6' },
timestamp: '2020-04-01T20:58:01.680186Z',
  attachments: [],
channelId: 'msteams',
}
````
3. Uninstall Bot. Not event fired. Expected: `membersRemoved` fired

If you install the Bot to a team, 
<img width="271" alt="Screen Shot 2020-04-01 at 2 01 29 PM" src="https://user-images.githubusercontent.com/1620357/78186362-7a21ce00-7421-11ea-892a-442b31da34f6.png">

then here is an event like so

```
 {"membersRemoved":[{"id":"28:f56a1d76-2630-4200-bedc-fdff8a7672a6"}],"type":"conversationUpdate","timestamp":"2020-04-01T20:57:25.8077876Z","sourceEvent":{"team":{"aadGroupId":"362c5f09-f9f7-49bc-8ad5-895d3a8761a4","name":"XXX","id":"19:1290d5cafeb545a1ae683b8e6eec09fe@thread.skype"},"eventType":"teamMemberRemoved",
``` 

####Code 

```
let builder = require('botbuilder');
let teams = require('botbuilder-teams');
const connector = new teams.TeamsChatConnector({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});
let bot = new builder.UniversalBot(connector, function (session) {
    // XXX
})
bot.on('conversationUpdate', function(message){
console.log('conversation update', JSON.stringify(message));
});
```

Update:
I found this in the document here https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-activities?view=azure-bot-service-3.0#conversationupdate

"The `conversationUpdate` event with the `membersRemoved` object in the payload is sent when **either your bot is removed from a team, or a user is removed from a team where a bot** has been added. "

So how do I stop sending message to user who uninstall the bot then?

**Comment by Subhasish-msft** [comment]
@nguyendn ,
The conversationUpdate event is sent in slightly different instances depending on context:

For a 1:1 conversation between the bot and a user (personal scope) the event is only sent the very first time the bot is installed. Technically, it is sent when the conversation is created between the bot and the user. If the user uninstalls the bot, this conversation is not deleted, so `conversationUpdate` event is not triggered.

In case of Group Chats and Channels the event will be sent each time the bot is installed. This is because each time the bot is uninstalled from this context, it is actually completely removed from the conversation, so an uninstall triggers the event.

**Comment by nguyendn** [comment]
@Subhasish-msft Thank you for your information. So how does the backend know when to stop sending messages to the user?

**Comment by Subhasish-msft** [comment]
You will face this issue only when you send proactive message. You could provide user a choice to opt out by sending another card.

**Comment by nguyendn** [comment]
@Subhasish-msft thank you!
