### ISSUE TITLE
How to configure Bot Framework C# project to send welcome message over Teams channel 

### ISSUE THREAD

**Issue by lopejum** [OfficeDev/BotBuilder-MicrosoftTeams#265]
Hello guys,

I developed a C# Bot and withing WebChat channel I'm sending a welcome message every time a user contacts my bot.

So, in the same way, I would like to have the same behavior when I publish the Teams channels and an user contacts for the first time my bot (no waiting until the user sends any message to the bot)

Thanks in advance!

Best regards
Lope

**Comment by lopejum** [comment]
Hello! Any news about this?
Thanks!

**Comment by Wajeed-msft** [comment]
@lopejum - You can send welcome message to channel when your App is installed to the team. In order to do that you need to get the [Get the user ID, team ID or channel ID](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#get-the-user-id-team-id-or-channel-id) which then can be used to [send welcome message](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#create-the-conversation). 

Here is documentation on sending proactive message: 
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet

Here is step by step guide on sending proactive message: https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-send-proactive

Please let us know if you are facing any issues or need more information.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
