### ISSUE TITLE
How to access address.serviceUrl without message

### ISSUE THREAD

**Issue by rqc** [OfficeDev/BotBuilder-MicrosoftTeams#47]
Hi,

The example [here](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/Node/samples/app.js) constructs dialogs using the `session.message.address.serviceUrl` parameter. In this example it makes sense to assume that this value will be in the context of a message, because it is in response to a user message. However, if I just want the bot to send a message or create a new conversation or channel on MS teams without the user sending a message first, how can I get the session context (`address.serviceUrl`) from the `connector` / `bot` objects directly?

**Comment by RamjotSingh** [comment]
Since user will always be the first one to contact the bot (either through team or direct conversation) you can store the service url on bot's side for future reference. For example if user is part of a team which the bot was added to and bot would like to start a direct conversation with the user, bot can use the same service url as in the team messages to start conversation with the user. Same goes for any action in the team too.
